# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
