# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='images/default-avatar.jpg', null=True,
                                    upload_to='images/user/'),
        ),
    ]
