# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_auto_20170115_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='blog.Post'),
        ),
    ]
