# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0013_auto_20170121_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='children', to='blog.Comment'),
        ),
    ]
