# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0013_auto_20170121_2211'),
        ('blog', '0015_auto_20170121_1419'),
    ]

    operations = [
    ]
